In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

In [3]:
input_file_1 = 'Zelma States/wisconsin-data-2023.csv'
input_file_2 = 'Zelma States/dc-data-2023.csv'
input_file_3 = 'Zelma States/kentucky-data-2023.csv'
input_file_4 = 'Zelma States/texas-data-2023.csv'

df_wi = pd.read_csv(input_file_1, low_memory=False)
df_dc = pd.read_csv(input_file_2, low_memory=False)
df_ky = pd.read_csv(input_file_3, low_memory=False)
df_tx = pd.read_csv(input_file_4, low_memory=False)

In [102]:
input_file_5 = "G:/Shared drives/OE_Data Sources/Summatives/WI/data_to_upload/wi2223.csv"
input_file_6 = "G:/Shared drives/OE_Data Sources/Summatives/TX/data_to_upload/tx_district2223.csv"
input_file_7 = "G:/Shared drives/OE_Data Sources/Summatives/KY/data_to_upload/ky2223upload.csv"
input_file_8 = "G:/Shared drives/OE_Data Sources/Summatives/DC/data_to_upload/dc2223upload.csv"

anet_wi = pd.read_csv(input_file_5, low_memory=False)
anet_tx = pd.read_csv(input_file_6, low_memory=False)
anet_ky = pd.read_csv(input_file_7, low_memory=False)
anet_dc = pd.read_csv(input_file_8, low_memory=False)

In [103]:
anet_wi

,Lookup,StateSchoolCode,SchoolName,State,SchoolYear,Grade,Subject,Breakdown,EnrolledCount,TestedCount,L1Count,L1Pct,L2Count,L2Pct,L3Count,L3Pct,L4Count,L4Pct,L5Count,L5Pct,L6Count,L6Pct,ApCount,ApPct,Percentile
0,WI00070020,70020,Abbotsford Elementary,WI,2023,3,ELA,All,39,38,13,0.342105,13,0.342105,11,0.289474,1,0.026316,NaN,NaN,NaN,NaN,12,0.315789,0.398408
1,WI00070020,70020,Abbotsford Elementary,WI,2023,3,ELA,ELL,25,25,11,0.440000,10,0.400000,4,0.160000,0,0.000000,NaN,NaN,NaN,NaN,4,0.160000,NaN
2,WI00070020,70020,Abbotsford Elementary,WI,2023,3,ELA,FRL,30,29,11,0.379310,11,0.379310,7,0.241379,0,0.000000,NaN,NaN,NaN,NaN,7,0.241379,NaN
3,WI00070020,70020,Abbotsford Elementary,WI,2023,3,ELA,Female,21,20,5,0.250000,10,0.500000,5,0.250000,0,0.000000,NaN,NaN,NaN,NaN,5,0.250000,NaN
4,WI00070020,70020,Abbotsford Elementary,WI,2023,3,ELA,Hispanic,28,27,11,0.407407,10,0.370370,6,0.222222,0,0.000000,NaN,NaN,NaN,NaN,6,0.222222,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122833,WI80278152,80278152,Carmen Middle School South,WI,2023,3-8,Math,Male,81,79,39,0.493671,28,0.354430,10,0.126582,2,0.025316,NaN,NaN,NaN,NaN,12,0.151899,NaN
122834,WI80278152,80278152,Carmen Middle School South,WI,2023,3-8,Math,SPED,6,6,5,0.833333,1,0.166667,0,0.000000,0,0.000000,NaN,NaN,NaN,NaN,0,0.000000,NaN
122835,WI80278152,80278152,Carmen Middle School South,WI,2023,3-8,Math,nonELL,90,87,37,0.425287,33,0.379310,14,0.160920,3,0.034483,NaN,NaN,NaN,NaN,17,0.195402,NaN
122836,WI80278152,80278152,Carmen Middle School South,WI,2023,3-8,Math,nonMigrant,170,166,91,0.548193,50,0.301205,22,0.132530,3,0.018072,NaN,NaN,NaN,NaN,25,0.150602,NaN
122837,WI80278152,80278152,Carmen Middle School South,WI,2023,3-8,Math,nonSPED,59,58,26,0.448276,19,0.327586,11,0.189655,2,0.034483,NaN,NaN,NaN,NaN,13,0.224138,NaN

In [4]:
df_wi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239206 entries, 0 to 239205
Data columns (total 48 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   State                        239206 non-null  object
 1   StateAbbrev                  239206 non-null  object
 2   StateFips                    239206 non-null  int64
 3   SchYear                      239206 non-null  object
 4   DataLevel                    239206 non-null  object
 5   DistName                     239206 non-null  object
 6   DistType                     238902 non-null  object
 7   SchName                      239206 non-null  object
 8   SchType                      165804 non-null  object
 9   NCESDistrictID               238902 non-null  float64
 10  StateAssignedDistID          238902 non-null  float64
 11  State_leaid                  238902 non-null  float64
 12  NCESSchoolID                 165804 non-null  object
 13  StateAssignedSchID           165804 non-null  float64
 14  seasch                       165804 non-null  float64
 15  DistCharter                  238902 non-null  object
 16  SchLevel                     165804 non-null  object
 17  SchVirtual                   165804 non-null  object
 18  CountyName                   238902 non-null  object
 19  CountyCode                   238902 non-null  float64
 20  AssmtName                    239206 non-null  object
 21  AssmtType                    239206 non-null  object
 22  Subject                      239206 non-null  object
 23  GradeLevel                   239206 non-null  object
 24  StudentGroup                 239206 non-null  object
 25  StudentGroup_TotalTested     239206 non-null  int64
 26  StudentSubGroup              239206 non-null  object
 27  StudentSubGroup_TotalTested  239206 non-null  object
 28  Lev1_count                   239206 non-null  object
 29  Lev1_percent                 239206 non-null  object
 30  Lev2_count                   239206 non-null  object
 31  Lev2_percent                 239206 non-null  object
 32  Lev3_count                   239206 non-null  object
 33  Lev3_percent                 239206 non-null  object
 34  Lev4_count                   239206 non-null  object
 35  Lev4_percent                 239206 non-null  object
 36  Lev5_count                   0 non-null       float64
 37  Lev5_percent                 0 non-null       float64
 38  AvgScaleScore                239206 non-null  object
 39  ProficiencyCriteria          239206 non-null  object
 40  ProficientOrAbove_count      239206 non-null  object
 41  ProficientOrAbove_percent    239206 non-null  object
 42  ParticipationRate            239206 non-null  object
 43  Flag_AssmtNameChange         239206 non-null  object
 44  Flag_CutScoreChange_ELA      239206 non-null  object
 45  Flag_CutScoreChange_math     239206 non-null  object
 46  Flag_CutScoreChange_read     0 non-null       float64
 47  Flag_CutScoreChange_oth      239206 non-null  object
dtypes: float64(9), int64(2), object(37)
memory usage: 87.6+ MB

In [5]:
df_dc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13238 entries, 0 to 13237
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   State                        13238 non-null  object
 1   StateAbbrev                  13238 non-null  object
 2   StateFips                    13238 non-null  int64
 3   SchYear                      13238 non-null  object
 4   DataLevel                    13238 non-null  object
 5   DistName                     13238 non-null  object
 6   DistType                     13070 non-null  object
 7   SchName                      13238 non-null  object
 8   SchType                      9753 non-null   object
 9   NCESDistrictID               13070 non-null  float64
 10  StateAssignedDistID          13070 non-null  float64
 11  State_leaid                  13070 non-null  object
 12  NCESSchoolID                 9753 non-null   float64
 13  StateAssignedSchID           9753 non-null   float64
 14  seasch                       9753 non-null   object
 15  DistCharter                  13070 non-null  object
 16  SchLevel                     9753 non-null   object
 17  SchVirtual                   9753 non-null   object
 18  CountyName                   13070 non-null  object
 19  CountyCode                   13070 non-null  float64
 20  AssmtName                    13238 non-null  object
 21  AssmtType                    13238 non-null  object
 22  Subject                      13238 non-null  object
 23  GradeLevel                   13238 non-null  object
 24  StudentGroup                 13238 non-null  object
 25  StudentGroup_TotalTested     13238 non-null  object
 26  StudentSubGroup              13238 non-null  object
 27  StudentSubGroup_TotalTested  13238 non-null  object
 28  Lev1_count                   13238 non-null  object
 29  Lev1_percent                 13238 non-null  object
 30  Lev2_count                   13238 non-null  object
 31  Lev2_percent                 13238 non-null  object
 32  Lev3_count                   13238 non-null  object
 33  Lev3_percent                 13238 non-null  object
 34  Lev4_count                   13238 non-null  object
 35  Lev4_percent                 13238 non-null  object
 36  Lev5_count                   13238 non-null  object
 37  Lev5_percent                 13238 non-null  object
 38  AvgScaleScore                13238 non-null  object
 39  ProficiencyCriteria          13238 non-null  object
 40  ProficientOrAbove_count      13238 non-null  object
 41  ProficientOrAbove_percent    13238 non-null  object
 42  ParticipationRate            13238 non-null  object
 43  Flag_AssmtNameChange         13238 non-null  object
 44  Flag_CutScoreChange_ELA      13238 non-null  object
 45  Flag_CutScoreChange_math     13238 non-null  object
 46  Flag_CutScoreChange_read     0 non-null      float64
 47  Flag_CutScoreChange_oth      0 non-null      float64
dtypes: float64(7), int64(1), object(40)
memory usage: 4.8+ MB

In [6]:
df_ky.shape

(193088, 48)

In [7]:
df_tx.shape

(1122640, 48)

In [8]:
df_wi.Subject.value_counts()

Subject
ela     89539
math    89539
sci     30064
soc     30064
Name: count, dtype: int64

In [9]:
df_wi.head()

,State,StateAbbrev,StateFips,SchYear,DataLevel,DistName,DistType,SchName,SchType,NCESDistrictID,StateAssignedDistID,State_leaid,NCESSchoolID,StateAssignedSchID,seasch,DistCharter,SchLevel,SchVirtual,CountyName,CountyCode,AssmtName,AssmtType,Subject,GradeLevel,StudentGroup,StudentGroup_TotalTested,StudentSubGroup,StudentSubGroup_TotalTested,Lev1_count,Lev1_percent,Lev2_count,Lev2_percent,Lev3_count,Lev3_percent,Lev4_count,Lev4_percent,Lev5_count,Lev5_percent,AvgScaleScore,ProficiencyCriteria,ProficientOrAbove_count,ProficientOrAbove_percent,ParticipationRate,Flag_AssmtNameChange,Flag_CutScoreChange_ELA,Flag_CutScoreChange_math,Flag_CutScoreChange_read,Flag_CutScoreChange_oth
0,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G03,All Students,54510,All Students,54510,13809,.2533296645,20050,.3678224087,17114,.313960731,3537,.0648871735,NaN,NaN,553.20,Levels 3 and 4,20651,.3788478971,.978266716,N,N,N,NaN,N
1,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G03,EL Status,54510,English Learner,4600,2252,.4895652235,1792,.3895652294,520,.1130434796,36,.0078260871,NaN,NaN,522.20,Levels 3 and 4,556,.1208695695,.939350605,N,N,N,NaN,N
2,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G03,EL Status,54510,English Proficient,49900,11555,.2315631211,18255,.3658316731,16589,.3324448764,3501,.0701603219,NaN,NaN,556.05,Levels 3 and 4,20090,.4026052058,.9820708036,N,N,N,NaN,N
3,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G03,EL Status,54510,Other,10,2,.200000003,3,.3000000119,5,.5,0,0,NaN,NaN,557.70,Levels 3 and 4,5,.5,.769230783,N,N,N,NaN,N
4,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G03,Economic Status,54510,Economically Disadvantaged,24319,9622,.3956577182,9475,.3896130621,4666,.1918664426,556,.0228627827,NaN,NaN,533.32,Levels 3 and 4,5222,.2147292197,.9725266099,N,N,N,NaN,N

In [10]:
df_wi.iloc[0]['StudentGroup_TotalTested'] * float(df_wi.iloc[0]['ParticipationRate'])

53325.318689160005

In [11]:
enroll_count_wi = df_wi[(df_wi['DataLevel'] == 'State') & (df_wi['StudentGroup'] == 'All Students') & (df_wi['Subject'].isin(['math', 'ela']))]

In [12]:
enroll_count_wi['StudentGroup_TotalTested'] * enroll_count_wi['ParticipationRate'].astype('float')

0      53325.318689
19     53738.619276
38     54271.808004
57     53980.916732
76     54662.781901
95     55816.927789
114    53784.130797
133    54077.762220
152    54663.815241
171    54308.197970
190    54945.500669
209    56022.024455
dtype: float64

In [13]:
enroll_count_wi

,State,StateAbbrev,StateFips,SchYear,DataLevel,DistName,DistType,SchName,SchType,NCESDistrictID,StateAssignedDistID,State_leaid,NCESSchoolID,StateAssignedSchID,seasch,DistCharter,SchLevel,SchVirtual,CountyName,CountyCode,AssmtName,AssmtType,Subject,GradeLevel,StudentGroup,StudentGroup_TotalTested,StudentSubGroup,StudentSubGroup_TotalTested,Lev1_count,Lev1_percent,Lev2_count,Lev2_percent,Lev3_count,Lev3_percent,Lev4_count,Lev4_percent,Lev5_count,Lev5_percent,AvgScaleScore,ProficiencyCriteria,ProficientOrAbove_count,ProficientOrAbove_percent,ParticipationRate,Flag_AssmtNameChange,Flag_CutScoreChange_ELA,Flag_CutScoreChange_math,Flag_CutScoreChange_read,Flag_CutScoreChange_oth
0,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G03,All Students,54510,All Students,54510,13809,.2533296645,20050,.3678224087,17114,.313960731,3537,.0648871735,NaN,NaN,553.20,Levels 3 and 4,20651,.3788478971,.978266716,N,N,N,NaN,N
19,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G04,All Students,54912,All Students,54912,12436,.226471439,17356,.3160693347,19320,.3518356681,5800,.1056235433,NaN,NaN,584.81,Levels 3 and 4,25120,.4574592113,.9786316156,N,N,N,NaN,N
38,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G05,All Students,55478,All Students,55478,15112,.2723962665,18629,.3357907534,18244,.328851074,3493,.0629618913,NaN,NaN,593.75,Levels 3 and 4,21737,.3918129802,.9782581925,N,N,N,NaN,N
57,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G06,All Students,55503,All Students,55503,13960,.2515179217,18995,.3422337472,17488,.3150820732,5060,.091166243,NaN,NaN,605.01,Levels 3 and 4,22548,.4062483311,.9725765586,N,N,N,NaN,N
76,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G07,All Students,56530,All Students,56530,13694,.2422430515,19582,.3464001417,18591,.3288696408,4663,.0824871734,NaN,NaN,622.79,Levels 3 and 4,23254,.4113568068,.9669694304,N,N,N,NaN,N
95,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,ela,G08,All Students,58294,All Students,58294,15689,.2691357732,20566,.3527978957,16514,.283288151,5525,.094778195,NaN,NaN,628.50,Levels 3 and 4,22039,.378066361,.9575072527,N,N,N,NaN,N
114,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,math,G03,All Students,54744,All Students,54744,12355,.2256868333,15679,.2864058018,19297,.3524952531,7413,.135412097,NaN,NaN,554.13,Levels 3 and 4,26710,.4879073501,.9824662209,N,N,N,NaN,N
133,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,math,G04,All Students,55085,All Students,55085,11228,.2038304508,18257,.3314332366,17330,.3146046996,8270,.150131613,NaN,NaN,577.93,Levels 3 and 4,25600,.4647363126,.9817148447,N,N,N,NaN,N
152,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,math,G05,All Students,55678,All Students,55678,13778,.247458607,14982,.2690829337,20184,.3625130355,6734,.1209454387,NaN,NaN,602.68,Levels 3 and 4,26918,.4834584594,.9817848206,N,N,N,NaN,N
171,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,math,G06,All Students,55671,All Students,55671,15093,.2711106241,16842,.3025273383,19699,.353846699,4037,.0725153163,NaN,NaN,611.70,Levels 3 and 4,23736,.4263620079,.975520432,N,N,N,NaN,N
190,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,math,G07,All Students,56676,All Students,56676,19887,.3508892655,16540,.2918342948,17607,.3106606007,2642,.0466158502,NaN,NaN,621.34,Levels 3 and 4,20249,.3572764397,.9694668055,N,N,N,NaN,N
209,Wisconsin,WI,55,2022-23,State,All Districts,NaN,All Schools,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forward,Regular,math,G08,All Students,58401,All Students,58401,20090,.3440009654,19745,.3380935192,14732,.2522559464,3834,.0656495616,NaN,NaN,639.10,Levels 3 and 4,18566,.3179055154,.9592648149,N,N,N,NaN,N

In [14]:
df_wi.StudentGroup.value_counts()

StudentGroup
RaceEth            88822
Economic Status    46284
Gender             46084
EL Status          36450
All Students       21566
Name: count, dtype: int64

## Data Filtering

In [20]:
df_wi = df_wi[df_wi['DataLevel'] == 'School']
df_ky = df_ky[df_ky['DataLevel'] == 'School']
df_dc = df_dc[df_dc['DataLevel'] == 'School']
df_tx = df_tx[df_tx['DataLevel'] == 'District']

In [22]:
subjects = ['math', 'ela']

df_wi = df_wi[df_wi['Subject'].isin(subjects)]
df_ky = df_ky[df_ky['Subject'].isin(subjects)]
df_dc = df_dc[df_dc['Subject'].isin(subjects)]
df_tx = df_tx[df_tx['Subject'].isin(subjects)]

In [63]:
df_wi = df_wi[df_wi['StudentSubGroup_TotalTested'].ne(0)]
df_ky = df_ky[df_ky['StudentSubGroup_TotalTested'].ne(0)]
df_dc = df_dc[df_dc['StudentSubGroup_TotalTested'].ne(0)]
df_tx = df_tx[df_tx['StudentSubGroup_TotalTested'].ne(0)]

In [64]:
df_wi

,State,StateAbbrev,StateFips,SchYear,DataLevel,DistName,DistType,SchName,SchType,NCESDistrictID,StateAssignedDistID,State_leaid,NCESSchoolID,StateAssignedSchID,seasch,DistCharter,SchLevel,SchVirtual,CountyName,CountyCode,AssmtName,AssmtType,Subject,GradeLevel,StudentGroup,StudentGroup_TotalTested,StudentSubGroup,StudentSubGroup_TotalTested,Lev1_count,Lev1_percent,Lev2_count,Lev2_percent,Lev3_count,Lev3_percent,Lev4_count,Lev4_percent,Lev5_count,Lev5_percent,AvgScaleScore,ProficiencyCriteria,ProficientOrAbove_count,ProficientOrAbove_percent,ParticipationRate,Flag_AssmtNameChange,Flag_CutScoreChange_ELA,Flag_CutScoreChange_math,Flag_CutScoreChange_read,Flag_CutScoreChange_oth
73402,Wisconsin,WI,55,2022-23,School,Abbotsford,Regular local school district,Abbotsford Elementary,Regular school,5500030.0,7.0,7.0,550003000001,20.0,20.0,No,Primary,Supplemental virtual,Clark County,55019.0,Forward,Regular,ela,G03,All Students,38,All Students,38,13,.3421052694,13,.3421052694,11,.2894736826,1,.0263157897,NaN,NaN,539.03,Levels 3 and 4,12,.3157894611,.9743589759,N,N,N,NaN,N
73403,Wisconsin,WI,55,2022-23,School,Abbotsford,Regular local school district,Abbotsford Elementary,Regular school,5500030.0,7.0,7.0,550003000001,20.0,20.0,No,Primary,Supplemental virtual,Clark County,55019.0,Forward,Regular,ela,G03,EL Status,38,English Learner,25,11,.4399999976,10,.400000006,4,.1599999964,0,0,NaN,NaN,522.92,Levels 3 and 4,4,.1599999964,1,N,N,N,NaN,N
73404,Wisconsin,WI,55,2022-23,School,Abbotsford,Regular local school district,Abbotsford Elementary,Regular school,5500030.0,7.0,7.0,550003000001,20.0,20.0,No,Primary,Supplemental virtual,Clark County,55019.0,Forward,Regular,ela,G03,EL Status,38,English Proficient,13,2,.1538461596,3,.2307692319,7,.538461566,1,.0769230798,NaN,NaN,570.00,Levels 3 and 4,8,.6153846383,.928571403,N,N,N,NaN,N
73405,Wisconsin,WI,55,2022-23,School,Abbotsford,Regular local school district,Abbotsford Elementary,Regular school,5500030.0,7.0,7.0,550003000001,20.0,20.0,No,Primary,Supplemental virtual,Clark County,55019.0,Forward,Regular,ela,G03,Economic Status,38,Economically Disadvantaged,29,11,.3793103397,11,.3793103397,7,.2413793057,0,0,NaN,NaN,530.45,Levels 3 and 4,7,.2413793057,.9666666389,N,N,N,NaN,N
73406,Wisconsin,WI,55,2022-23,School,Abbotsford,Regular local school district,Abbotsford Elementary,Regular school,5500030.0,7.0,7.0,550003000001,20.0,20.0,No,Primary,Supplemental virtual,Clark County,55019.0,Forward,Regular,ela,G03,Economic Status,38,Not Economically Disadvantaged,9,2,.2222222239,2,.2222222239,4,.4444444478,1,.1111111119,NaN,NaN,566.67,Levels 3 and 4,5,.555555582,1,N,N,N,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239165,Wisconsin,WI,55,2022-23,School,Yorkville J2,Regular local school district,Yorkville Elementary,Regular school,5517220.0,6748.0,6748.0,551722002230,20.0,20.0,No,Primary,No,Racine County,55101.0,Forward,Regular,math,G08,Economic Status,67,Not Economically Disadvantaged,58,8,.137931034,23,.3965517282,21,.3620689511,6,.1034482792,NaN,NaN,663.81,Levels 3 and 4,27,.4655172229,1,N,N,N,NaN,N
239166,Wisconsin,WI,55,2022-23,School,Yorkville J2,Regular local school district,Yorkville Elementary,Regular school,5517220.0,6748.0,6748.0,551722002230,20.0,20.0,No,Primary,No,Racine County,55101.0,Forward,Regular,math,G08,Gender,67,Female,35,2,.0571428575,15,.4285714328,15,.4285714328,3,.0857142881,NaN,NaN,666.60,Levels 3 and 4,18,.5142857432,1,N,N,N,NaN,N
239167,Wisconsin,WI,55,2022-23,School,Yorkville J2,Regular local school district,Yorkville Elementary,Regular school,5517220.0,6748.0,6748.0,551722002230,20.0,20.0,No,Primary,No,Racine County,55101.0,Forward,Regular,math,G08,Gender,67,Male,32,8,.25,15,.46875,6,.1875,3,.09375,NaN,NaN,650.59,Levels 3 and 4,9,.28125,1,N,N,N,NaN,N
239168,Wisconsin,WI,55,2022-23,School,Yorkville J2,Regular local school district,Yorkville Elementary,Regular school,5517220.0,6748.0,6748.0,551722002230,20.0,20.0,No,Primary,No,Racine County,55101.0,Forward,Regular,math,G08,RaceEth,67,Hispanic or Latino,*,*,*,*,*,*,*,*,*,NaN,NaN,*,Levels 3 and 4,*,*,*,N,N,N,NaN,N
239169,Wisconsin,WI,55,2022-23,School,Yorkville J2,Regular local school district,Yorkville Elementary,Regular school,5517220.0,6748.0,6748.0,551722002230,20.0,20.0,No,Primary,No,Racine County,55101.0,Forward,Regular,math,G08,RaceEth,67,White,*,*,*,*,*,*,*,*,*,NaN,NaN,*,Levels 3 and 4,*,*,*,N,N,N,NaN,N

## Data Cleaning

In [65]:
print(df_wi.duplicated().sum())
print(df_dc.duplicated().sum())
print(df_tx.duplicated().sum())
print(df_ky.duplicated().sum())

0
0
0
0

The most important value we care about is the ProficientOrAbove count. Since there are no nulls between these states for that column and the null values only exist in columns that don't affect our analysis we will keep them to maintain as much usable data as possible.

In [66]:
df_wi.isna().sum()

State                               0
StateAbbrev                         0
StateFips                           0
SchYear                             0
DataLevel                           0
DistName                            0
DistType                            0
SchName                             0
SchType                             0
NCESDistrictID                      0
StateAssignedDistID                 0
State_leaid                         0
NCESSchoolID                        0
StateAssignedSchID                  0
seasch                              0
DistCharter                         0
SchLevel                            0
SchVirtual                          0
CountyName                          0
CountyCode                          0
AssmtName                           0
AssmtType                           0
Subject                             0
GradeLevel                          0
StudentGroup                        0
StudentGroup_TotalTested            0
StudentSubGroup                     0
StudentSubGroup_TotalTested         0
Lev1_count                          0
Lev1_percent                        0
Lev2_count                          0
Lev2_percent                        0
Lev3_count                          0
Lev3_percent                        0
Lev4_count                          0
Lev4_percent                        0
Lev5_count                     124012
Lev5_percent                   124012
AvgScaleScore                       0
ProficiencyCriteria                 0
ProficientOrAbove_count             0
ProficientOrAbove_percent           0
ParticipationRate                   0
Flag_AssmtNameChange                0
Flag_CutScoreChange_ELA             0
Flag_CutScoreChange_math            0
Flag_CutScoreChange_read       124012
Flag_CutScoreChange_oth             0
dtype: int64

In [67]:
df_dc.isna().sum()

State                             0
StateAbbrev                       0
StateFips                         0
SchYear                           0
DataLevel                         0
DistName                          0
DistType                          0
SchName                           0
SchType                           0
NCESDistrictID                    0
StateAssignedDistID               0
State_leaid                       0
NCESSchoolID                      0
StateAssignedSchID                0
seasch                            0
DistCharter                       0
SchLevel                          0
SchVirtual                        0
CountyName                        0
CountyCode                        0
AssmtName                         0
AssmtType                         0
Subject                           0
GradeLevel                        0
StudentGroup                      0
StudentGroup_TotalTested          0
StudentSubGroup                   0
StudentSubGroup_TotalTested       0
Lev1_count                        0
Lev1_percent                      0
Lev2_count                        0
Lev2_percent                      0
Lev3_count                        0
Lev3_percent                      0
Lev4_count                        0
Lev4_percent                      0
Lev5_count                        0
Lev5_percent                      0
AvgScaleScore                     0
ProficiencyCriteria               0
ProficientOrAbove_count           0
ProficientOrAbove_percent         0
ParticipationRate                 0
Flag_AssmtNameChange              0
Flag_CutScoreChange_ELA           0
Flag_CutScoreChange_math          0
Flag_CutScoreChange_read       9753
Flag_CutScoreChange_oth        9753
dtype: int64

Remember, df_tx was filtered at the District Level so all the School level identifiers will be null

In [68]:
df_tx.isna().sum()

State                               0
StateAbbrev                         0
StateFips                           0
SchYear                             0
DataLevel                           0
DistName                            0
DistType                            0
SchName                             0
SchType                        154287
NCESDistrictID                      0
StateAssignedDistID                 0
State_leaid                         0
NCESSchoolID                   154287
StateAssignedSchID             154287
seasch                         154287
DistCharter                         0
SchLevel                       154287
SchVirtual                     154287
CountyName                          0
CountyCode                          0
AssmtName                           0
AssmtType                           0
Subject                             0
GradeLevel                          0
StudentGroup                        0
StudentGroup_TotalTested            0
StudentSubGroup                     0
StudentSubGroup_TotalTested         0
Lev1_count                          0
Lev1_percent                        0
Lev2_count                          0
Lev2_percent                        0
Lev3_count                          0
Lev3_percent                        0
Lev4_count                          0
Lev4_percent                        0
Lev5_count                     154287
Lev5_percent                   154287
AvgScaleScore                       0
ProficiencyCriteria                 0
ProficientOrAbove_count             0
ProficientOrAbove_percent           0
ParticipationRate                   0
Flag_AssmtNameChange                0
Flag_CutScoreChange_ELA             0
Flag_CutScoreChange_math            0
Flag_CutScoreChange_read       154287
Flag_CutScoreChange_oth             0
dtype: int64

In [69]:
df_ky.isna().sum()

State                              0
StateAbbrev                        0
StateFips                          0
SchYear                            0
DataLevel                          0
DistName                           0
DistType                           0
SchName                            0
SchType                            0
NCESDistrictID                     0
StateAssignedDistID                0
State_leaid                        0
NCESSchoolID                       0
StateAssignedSchID                 0
seasch                             0
DistCharter                        0
SchLevel                           0
SchVirtual                         0
CountyName                         0
CountyCode                         0
AssmtName                          0
AssmtType                          0
Subject                            0
GradeLevel                         0
StudentGroup                       0
StudentGroup_TotalTested           0
StudentSubGroup                    0
StudentSubGroup_TotalTested        0
Lev1_count                         0
Lev1_percent                       0
Lev2_count                         0
Lev2_percent                       0
Lev3_count                         0
Lev3_percent                       0
Lev4_count                         0
Lev4_percent                       0
Lev5_count                         0
Lev5_percent                       0
AvgScaleScore                      0
ProficiencyCriteria                0
ProficientOrAbove_count            0
ProficientOrAbove_percent          0
ParticipationRate                  0
Flag_AssmtNameChange               0
Flag_CutScoreChange_ELA            0
Flag_CutScoreChange_math           0
Flag_CutScoreChange_read       99428
Flag_CutScoreChange_oth            0
dtype: int64

### Suppressed and Missing Data

Keeping suppressed and missing data separate to maybe see some further analysis as to what makes them differ.

In [70]:
df_wi.eq('*').sum()

State                              0
StateAbbrev                        0
StateFips                          0
SchYear                            0
DataLevel                          0
DistName                           0
DistType                           0
SchName                            0
SchType                            0
NCESDistrictID                     0
StateAssignedDistID                0
State_leaid                        0
NCESSchoolID                       0
StateAssignedSchID                 0
seasch                             0
DistCharter                        0
SchLevel                           0
SchVirtual                         0
CountyName                         0
CountyCode                         0
AssmtName                          0
AssmtType                          0
Subject                            0
GradeLevel                         0
StudentGroup                       0
StudentGroup_TotalTested           0
StudentSubGroup                    0
StudentSubGroup_TotalTested    57266
Lev1_count                     57266
Lev1_percent                   57266
Lev2_count                     57266
Lev2_percent                   57266
Lev3_count                     57266
Lev3_percent                   57266
Lev4_count                     57266
Lev4_percent                   57266
Lev5_count                         0
Lev5_percent                       0
AvgScaleScore                  57266
ProficiencyCriteria                0
ProficientOrAbove_count        57266
ProficientOrAbove_percent      57266
ParticipationRate              57266
Flag_AssmtNameChange               0
Flag_CutScoreChange_ELA            0
Flag_CutScoreChange_math           0
Flag_CutScoreChange_read           0
Flag_CutScoreChange_oth            0
dtype: int64

In [71]:
df_wi.eq('--').sum()

State                          0
StateAbbrev                    0
StateFips                      0
SchYear                        0
DataLevel                      0
DistName                       0
DistType                       0
SchName                        0
SchType                        0
NCESDistrictID                 0
StateAssignedDistID            0
State_leaid                    0
NCESSchoolID                   0
StateAssignedSchID             0
seasch                         0
DistCharter                    0
SchLevel                       0
SchVirtual                     0
CountyName                     0
CountyCode                     0
AssmtName                      0
AssmtType                      0
Subject                        0
GradeLevel                     0
StudentGroup                   0
StudentGroup_TotalTested       0
StudentSubGroup                0
StudentSubGroup_TotalTested    0
Lev1_count                     0
Lev1_percent                   0
Lev2_count                     0
Lev2_percent                   0
Lev3_count                     0
Lev3_percent                   0
Lev4_count                     0
Lev4_percent                   0
Lev5_count                     0
Lev5_percent                   0
AvgScaleScore                  0
ProficiencyCriteria            0
ProficientOrAbove_count        0
ProficientOrAbove_percent      0
ParticipationRate              0
Flag_AssmtNameChange           0
Flag_CutScoreChange_ELA        0
Flag_CutScoreChange_math       0
Flag_CutScoreChange_read       0
Flag_CutScoreChange_oth        0
dtype: int64

In [72]:
df_tx.eq('*').sum()

State                              0
StateAbbrev                        0
StateFips                          0
SchYear                            0
DataLevel                          0
DistName                           0
DistType                           0
SchName                            0
SchType                            0
NCESDistrictID                     0
StateAssignedDistID                0
State_leaid                        0
NCESSchoolID                       0
StateAssignedSchID                 0
seasch                             0
DistCharter                        0
SchLevel                           0
SchVirtual                         0
CountyName                         0
CountyCode                         0
AssmtName                          0
AssmtType                          0
Subject                            0
GradeLevel                         0
StudentGroup                       0
StudentGroup_TotalTested           0
StudentSubGroup                    0
StudentSubGroup_TotalTested        0
Lev1_count                     31939
Lev1_percent                   31939
Lev2_count                     31939
Lev2_percent                   31939
Lev3_count                     31939
Lev3_percent                   31939
Lev4_count                     31939
Lev4_percent                   31939
Lev5_count                         0
Lev5_percent                       0
AvgScaleScore                  31939
ProficiencyCriteria                0
ProficientOrAbove_count        31939
ProficientOrAbove_percent      31939
ParticipationRate                  0
Flag_AssmtNameChange               0
Flag_CutScoreChange_ELA            0
Flag_CutScoreChange_math           0
Flag_CutScoreChange_read           0
Flag_CutScoreChange_oth            0
dtype: int64

In [73]:
df_tx.eq('--').sum()

State                               0
StateAbbrev                         0
StateFips                           0
SchYear                             0
DataLevel                           0
DistName                            0
DistType                            0
SchName                             0
SchType                             0
NCESDistrictID                      0
StateAssignedDistID                 0
State_leaid                         0
NCESSchoolID                        0
StateAssignedSchID                  0
seasch                              0
DistCharter                         0
SchLevel                            0
SchVirtual                          0
CountyName                          0
CountyCode                          0
AssmtName                           0
AssmtType                           0
Subject                             0
GradeLevel                          0
StudentGroup                        0
StudentGroup_TotalTested            0
StudentSubGroup                     0
StudentSubGroup_TotalTested         0
Lev1_count                          0
Lev1_percent                        0
Lev2_count                          0
Lev2_percent                        0
Lev3_count                          0
Lev3_percent                        0
Lev4_count                          0
Lev4_percent                        0
Lev5_count                          0
Lev5_percent                        0
AvgScaleScore                       0
ProficiencyCriteria                 0
ProficientOrAbove_count             0
ProficientOrAbove_percent           0
ParticipationRate              140406
Flag_AssmtNameChange                0
Flag_CutScoreChange_ELA             0
Flag_CutScoreChange_math            0
Flag_CutScoreChange_read            0
Flag_CutScoreChange_oth             0
dtype: int64

In [74]:
df_ky.eq('*').sum()

State                              0
StateAbbrev                        0
StateFips                          0
SchYear                            0
DataLevel                          0
DistName                           0
DistType                           0
SchName                            0
SchType                            0
NCESDistrictID                     0
StateAssignedDistID                0
State_leaid                        0
NCESSchoolID                       0
StateAssignedSchID                 0
seasch                             0
DistCharter                        0
SchLevel                           0
SchVirtual                         0
CountyName                         0
CountyCode                         0
AssmtName                          0
AssmtType                          0
Subject                            0
GradeLevel                         0
StudentGroup                       0
StudentGroup_TotalTested           0
StudentSubGroup                    0
StudentSubGroup_TotalTested        0
Lev1_count                         0
Lev1_percent                   59275
Lev2_count                         0
Lev2_percent                   59275
Lev3_count                         0
Lev3_percent                   59275
Lev4_count                         0
Lev4_percent                   59275
Lev5_count                         0
Lev5_percent                       0
AvgScaleScore                      0
ProficiencyCriteria                0
ProficientOrAbove_count            0
ProficientOrAbove_percent      59275
ParticipationRate                  0
Flag_AssmtNameChange               0
Flag_CutScoreChange_ELA            0
Flag_CutScoreChange_math           0
Flag_CutScoreChange_read           0
Flag_CutScoreChange_oth            0
dtype: int64

In [75]:
df_ky.eq('--').sum()

State                              0
StateAbbrev                        0
StateFips                          0
SchYear                            0
DataLevel                          0
DistName                           0
DistType                           0
SchName                            0
SchType                            0
NCESDistrictID                     0
StateAssignedDistID                0
State_leaid                        0
NCESSchoolID                       0
StateAssignedSchID                 0
seasch                             0
DistCharter                        0
SchLevel                           0
SchVirtual                         0
CountyName                         0
CountyCode                         0
AssmtName                          0
AssmtType                          0
Subject                            0
GradeLevel                         0
StudentGroup                       0
StudentGroup_TotalTested       29088
StudentSubGroup                    0
StudentSubGroup_TotalTested    29088
Lev1_count                     99428
Lev1_percent                       0
Lev2_count                     99428
Lev2_percent                       0
Lev3_count                     99428
Lev3_percent                       0
Lev4_count                     99428
Lev4_percent                       0
Lev5_count                     99428
Lev5_percent                   99428
AvgScaleScore                  99428
ProficiencyCriteria                0
ProficientOrAbove_count        99428
ProficientOrAbove_percent          0
ParticipationRate              99428
Flag_AssmtNameChange               0
Flag_CutScoreChange_ELA            0
Flag_CutScoreChange_math           0
Flag_CutScoreChange_read           0
Flag_CutScoreChange_oth            0
dtype: int64

In [76]:
df_dc.eq('*').sum()

State                             0
StateAbbrev                       0
StateFips                         0
SchYear                           0
DataLevel                         0
DistName                          0
DistType                          0
SchName                           0
SchType                           0
NCESDistrictID                    0
StateAssignedDistID               0
State_leaid                       0
NCESSchoolID                      0
StateAssignedSchID                0
seasch                            0
DistCharter                       0
SchLevel                          0
SchVirtual                        0
CountyName                        0
CountyCode                        0
AssmtName                         0
AssmtType                         0
Subject                           0
GradeLevel                        0
StudentGroup                      0
StudentGroup_TotalTested       3199
StudentSubGroup                   0
StudentSubGroup_TotalTested    5010
Lev1_count                     6389
Lev1_percent                   5483
Lev2_count                     6204
Lev2_percent                   5606
Lev3_count                     6120
Lev3_percent                   5549
Lev4_count                     9021
Lev4_percent                   7669
Lev5_count                     9021
Lev5_percent                   4168
AvgScaleScore                     0
ProficiencyCriteria               0
ProficientOrAbove_count        9021
ProficientOrAbove_percent      7687
ParticipationRate              3721
Flag_AssmtNameChange              0
Flag_CutScoreChange_ELA           0
Flag_CutScoreChange_math          0
Flag_CutScoreChange_read          0
Flag_CutScoreChange_oth           0
dtype: int64

In [77]:
df_dc.eq('--').sum()

State                             0
StateAbbrev                       0
StateFips                         0
SchYear                           0
DataLevel                         0
DistName                          0
DistType                          0
SchName                           0
SchType                           0
NCESDistrictID                    0
StateAssignedDistID               0
State_leaid                       0
NCESSchoolID                      0
StateAssignedSchID                0
seasch                            0
DistCharter                       0
SchLevel                          0
SchVirtual                        0
CountyName                        0
CountyCode                        0
AssmtName                         0
AssmtType                         0
Subject                           0
GradeLevel                        0
StudentGroup                      0
StudentGroup_TotalTested          0
StudentSubGroup                   0
StudentSubGroup_TotalTested       0
Lev1_count                        0
Lev1_percent                      0
Lev2_count                        0
Lev2_percent                      0
Lev3_count                        0
Lev3_percent                      0
Lev4_count                        0
Lev4_percent                      0
Lev5_count                        0
Lev5_percent                      0
AvgScaleScore                  9753
ProficiencyCriteria               0
ProficientOrAbove_count           0
ProficientOrAbove_percent         0
ParticipationRate                 0
Flag_AssmtNameChange              0
Flag_CutScoreChange_ELA           0
Flag_CutScoreChange_math          0
Flag_CutScoreChange_read          0
Flag_CutScoreChange_oth           0
dtype: int64

In [78]:
nans = ['*', '--']

In [ ]:
## Maybe add some code to catch instances where you can calculate Proficiency counts/Percentages

In [79]:
clean_wi = df_wi[~df_wi['ProficientOrAbove_count'].isin(nans)]
suppressed_wi = df_wi['ProficientOrAbove_count'].eq('*').sum()
clean_wi.shape

(66746, 48)

In [80]:
suppressed_wi

57266

In [81]:
clean_dc = df_dc[~df_dc['ProficientOrAbove_count'].isin(nans)]
suppressed_dc = df_dc['ProficientOrAbove_count'].eq('*').sum()

# Kentucky is unique in that it only has percent values, no counts
clean_ky = df_ky[~df_ky['ProficientOrAbove_percent'].isin(nans)]
suppressed_ky = df_ky['ProficientOrAbove_percent'].eq('*').sum()

clean_tx = df_tx[~df_tx['ProficientOrAbove_count'].isin(nans)]
suppressed_tx = df_tx['ProficientOrAbove_count'].eq('*').sum()

In [82]:
print(clean_dc.shape)
print(clean_ky.shape)
print(clean_tx.shape)

(732, 48)
(40153, 48)
(122348, 48)

In [83]:
print(suppressed_dc)
print(suppressed_ky)
print(suppressed_tx)

9021
59275
31939

All but KY has clean StudentSubGroup counts, but that is okay since we already knew KY only has percentages. If we wanted to calculated Proficiency Counts than this would be an issue, but since the Proficiency rate is the most important we can ignore this for the sake of maintaining maximal usable data.

In [91]:
clean_wi['StudentSubGroup_TotalTested'].isin(nans).sum()

0

In [92]:
clean_tx['StudentSubGroup_TotalTested'].isin(nans).sum()

0

In [93]:
clean_dc['StudentSubGroup_TotalTested'].isin(nans).sum()

0

In [94]:
clean_ky['StudentSubGroup_TotalTested'].isin(nans).sum()

15715

## Tabulate Results

In [121]:
# Let's filter out aggregate values from ANet records for a more fair comparison
filtered_anet_wi = anet_wi[anet_wi['Grade'].ne('3-8')]
filtered_anet_ky = anet_ky[anet_ky['Grade'].ne('3-8')]
filtered_anet_dc = anet_dc[anet_dc['Grade'].ne('All')]
filtered_anet_tx = anet_tx[anet_tx['Grade'].ne('3-8')]

In [126]:
filtered_anet_wi.Grade.value_counts()

Grade
3    18988
4    18404
5    17644
6    12138
8    11684
7    11536
Name: count, dtype: int64

In [127]:
states = ['WI', 'KY', 'DC', 'TX']
anet_records = [filtered_anet_wi.shape[0], filtered_anet_ky.shape[0], filtered_anet_dc.shape[0], filtered_anet_tx.shape[0]]
zelma_records = [clean_wi.shape[0], clean_ky.shape[0], clean_dc.shape[0], clean_tx.shape[0]]
df_records = pd.DataFrame(data={'ANet': anet_records, 'Zelma': zelma_records}, index=states)

In [128]:
df_records

      ANet   Zelma
WI   90394   66746
KY   73563   40153
DC    9477     732
TX  222304  122348